server:
    verbosity: 1
    interface: 127.0.0.1
    port: 53
    do-daemonize: no
    username: ""
    chroot: ""
    directory: "/etc/unbound"
    pidfile: ""
    root-hints: "/etc/unbound/root.hints"

    # Rekursive Auflösung aktiv
    do-not-query-localhost: no
    harden-glue: yes
    harden-dnssec-stripped: yes
    use-caps-for-id: yes
    prefetch: yes
    cache-min-ttl: 0
    cache-max-ttl: 86400

    # Logging (hilft beim Debuggen)
    log-queries: no
    log-replies: no

remote-control:
    control-enable: no
